"""add_historical_ml_id_to_clinics

Revision ID: d4cf24ab11e7
Revises: a3e456140034
Create Date: 2026-04-07 19:36:47.129170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cf24ab11e7'
down_revision: Union[str, None] = 'a3e456140034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('historical_ml_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'historical_ml_id')
    # ### end Alembic commands ###
