"""add_ticket_number_to_visits

Revision ID: e512aa1e7f4f
Revises: 152980aeb2d3
Create Date: 2026-04-09 02:04:48.803673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e512aa1e7f4f'
down_revision: Union[str, None] = '152980aeb2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('ticket_number', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_visits_ticket_number'), 'visits', ['ticket_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_ticket_number'), table_name='visits')
    op.drop_column('visits', 'ticket_number')
    # ### end Alembic commands ###
