"""
Bulk check-in script — seeds realistic patient visits for demo/testing.
Usage: python seed_checkins.py [--api http://localhost:8000]

Each patient gets 2-4 random studies. The script uses the real Culiacán clinic
UUIDs generated by seed_real_data.py (stable, deterministic UUIDs).
"""

import asyncio
import random
import sys
import uuid
from pathlib import Path

import httpx

API_DIR = Path(__file__).resolve().parent
sys.path.append(str(API_DIR))
from seed_real_data import get_stable_uuid  # noqa: E402

API_URL = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8000"

CLINIC_ID = str(get_stable_uuid("clinic", 1))


async def fetch_area_ids() -> list[str]:
    from sqlalchemy import select
    from app.core.database import AsyncSessionLocal
    from app.models.models import ClinicalArea

    async with AsyncSessionLocal() as db:
        r = await db.execute(
            select(ClinicalArea).where(
                ClinicalArea.clinic_id == uuid.UUID(CLINIC_ID),
                ClinicalArea.active.is_(True),
            )
        )
        areas = r.scalars().all()
        for a in areas:
            print(f"  {a.name} ({a.study_type}): {a.id}")
        return [str(a.id) for a in areas]

PATIENTS = [
    ("María García López",      "+521234567801"),
    ("José Hernández Ruiz",     "+521234567802"),
    ("Ana Martínez Pérez",      "+521234567803"),
    ("Carlos Rodríguez Sánchez","+521234567804"),
    ("Laura González Torres",   "+521234567805"),
    ("Miguel Flores Ramírez",   "+521234567806"),
    ("Patricia López Jiménez",  "+521234567807"),
    ("Roberto Morales Castro",  "+521234567808"),
    ("Sofía Díaz Vargas",       "+521234567809"),
    ("Fernando Reyes Mendoza",  "+521234567810"),
    ("Elena Gutiérrez Serrano", "+521234567811"),
    ("Alejandro Cruz Vega",     "+521234567812"),
]


async def checkin(client: httpx.AsyncClient, name: str, phone: str, area_ids: list[str]) -> dict | None:
    # Pick 2-4 random areas (no repeats)
    n = random.randint(2, min(4, len(area_ids)))
    study_ids = random.sample(area_ids, n)

    payload = {
        "phone_number": phone,
        "clinic_id": CLINIC_ID,
        "study_ids": study_ids,
        "has_appointment": random.choice([True, False]),
        "is_urgent": random.random() < 0.15,
    }

    try:
        r = await client.post(f"{API_URL}/api/v1/visits/check-in", json=payload, timeout=15)
        if r.status_code in (200, 201):
            data = r.json()
            steps = ", ".join(s["area_name"] for s in data.get("sequence", []))
            print(f"  ✓ {name} → {steps} ({data['total_estimated_minutes']} min)")
            return data
        else:
            print(f"  ✗ {name}: HTTP {r.status_code} — {r.text[:120]}")
    except Exception as e:
        print(f"  ✗ {name}: {e}")
    return None


async def main():
    print(f"Checking in {len(PATIENTS)} patients against {API_URL}")
    print(f"Clinic: {CLINIC_ID}")
    print("Fetching areas from DB...")
    area_ids = await fetch_area_ids()
    if not area_ids:
        print("No active areas found — run seed_real_data.py first.")
        return
    print()

    async with httpx.AsyncClient() as client:
        for name, phone in PATIENTS:
            await checkin(client, name, phone, area_ids)
            await asyncio.sleep(0.3)

    print("\nDone. Refresh the doctor dashboard to see the queue.")


if __name__ == "__main__":
    asyncio.run(main())
